// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nkztXr54TPnnkqx_udMG8weNfHNX-50',
    appId: '1:345848029681:web:fe818b87e2d2933d692450',
    messagingSenderId: '345848029681',
    projectId: 'kulu-f495f',
    authDomain: 'kulu-f495f.firebaseapp.com',
    storageBucket: 'kulu-f495f.firebasestorage.app',
    measurementId: 'G-ZPYWWQP8VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_osdns3ofJjzxx-CVAyl-I33SiVacPA',
    appId: '1:345848029681:android:bbde7391ae542fad692450',
    messagingSenderId: '345848029681',
    projectId: 'kulu-f495f',
    storageBucket: 'kulu-f495f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZXUSREmadeRc-SFvcwKgDzlv4rY8D8U',
    appId: '1:345848029681:ios:87a934f3b8ee6471692450',
    messagingSenderId: '345848029681',
    projectId: 'kulu-f495f',
    storageBucket: 'kulu-f495f.firebasestorage.app',
    iosBundleId: 'com.example.kuluapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZXUSREmadeRc-SFvcwKgDzlv4rY8D8U',
    appId: '1:345848029681:ios:c03747442ced8b86692450',
    messagingSenderId: '345848029681',
    projectId: 'kulu-f495f',
    storageBucket: 'kulu-f495f.firebasestorage.app',
    iosBundleId: 'com.kulu.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7nkztXr54TPnnkqx_udMG8weNfHNX-50',
    appId: '1:345848029681:web:a244a4ebc86e9dc5692450',
    messagingSenderId: '345848029681',
    projectId: 'kulu-f495f',
    authDomain: 'kulu-f495f.firebaseapp.com',
    storageBucket: 'kulu-f495f.firebasestorage.app',
    measurementId: 'G-MFLRKZ8EWS',
  );
}
